# -*- coding: utf-8 -*-
"""runnables.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qJGWpxg2JKmDESGY9f7Edp8zkGQIwOOQ
"""

from abc import ABC,abstractmethod

class Runnable(ABC):
  abstractmethod
  def invoke(input_data):
    pass

import random

class LLM:
  def __init__(self):
    print("LLM is created")

  def invoke(self,prompt):
    response_list= [
        'delhi is capital of india',
        'ipl is a cricket legaue'
    ]

    return {'response': random.choice(response_list)}

  def predict(self,prompt):

    response_list= [
        'delhi is capital of india',
        'ipl is a cricket legaue'
    ]

    return {'response': random.choice(response_list)}

llm=LLM()

llm.predict('what is capital of india')

class PromptTemplateSumma:

  def __init__(self,template,input_variables):
    self.template=template
    self.input_variables=input_variables

  def format(self,input_dict):
    return self.template.format(**input_dict)

template=PromptTemplateSumma(
    template='what is capital of {country}',
    input_variables=['country']
)

prompt=template.format({'country':'india'})

llm=LLM()

llm.predict(prompt)

"""another way to do it"""

class NakilliLLMChain:
  def __init__(self,llm,prompt):
    self.llm=llm
    self.prompt=prompt

  def run(self,input_dict):
    final_prompt=self.prompt.format(input_dict)
    result=self.llm.predict(final_prompt)
    return result['response']

class PromptTemplateSumma:

  def __init__(self,template,input_variables):
    self.template=template
    self.input_variables=input_variables

  def format(self,input_dict):
    return self.template.format(**input_dict)

llm=LLM()

chain=NakilliLLMChain(llm,template)
chain.run({'country':'india'})

# ------------------------------------------------------

class RunnableConnector(Runnable):
  def _init_(se)

"""I havent understood it completely
  It is confusing
  SO i just copied the code here for now
  I will revisit it later
  I have read some articles on runnables and chains
  I will try to understand it better

"""

